import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { getCurrentUser } from "@/lib/auth";
import { db, users } from "@/db";
import { eq } from "drizzle-orm";
import VerificationBanner from "@/components/verification-banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Check if user is authenticated and not verified
  let showVerificationBanner = false;
  
  try {
    const currentUser = await getCurrentUser();
    
    if (currentUser) {
      const user = await db.query.users.findFirst({
        where: eq(users.id, currentUser.userId),
      });
      
      if (user && !user.emailVerified) {
        showVerificationBanner = true;
      }
    }
  } catch (error) {
    // Silently fail - banner just won't show
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showVerificationBanner && <VerificationBanner />}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
